version: '3.9'
services:
  private_gpt:
    container_name: private_gpt
    build: .
    restart: always
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
    ports:
      - "8001:8080"
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: local
    networks:
      - db

networks:
  db:
    driver: bridge