server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8080}

llm:
  mode: ${PGPT_MODE:local}
  max_new_tokens: 1024
  context_window: 3900

local:
  llm_hf_repo_id: ${PGPT_HF_REPO_ID:IlyaGusev/saiga2_7b_gguf}
  llm_hf_model_file: ${PGPT_HF_MODEL_FILE:model-q4_K.gguf}
  embedding_hf_model_name: ${PGPT_EMBEDDING_HF_MODEL_NAME:sentence-transformers/paraphrase-multilingual-mpnet-base-v2}

sagemaker:
  llm_endpoint_name: ${PGPT_SAGEMAKER_LLM_ENDPOINT_NAME:}
  embedding_endpoint_name: ${PGPT_SAGEMAKER_EMBEDDING_ENDPOINT_NAME:}

ui:
  enabled: true
  path: /