server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8080}

llm:
  mode: ${PGPT_MODE:local}
  max_new_tokens: 1024
  context_window: 5000

local:
  llm_hf_repo_id: ${PGPT_HF_REPO_ID:IlyaGusev/saiga2_13b_gguf}
  llm_hf_model_file: ${PGPT_HF_MODEL_FILE:model-q5_K.gguf}
  embedding_hf_model_name: ${PGPT_EMBEDDING_HF_MODEL_NAME:sentence-transformers/paraphrase-multilingual-mpnet-base-v2}

sagemaker:
  llm_endpoint_name: ${PGPT_SAGEMAKER_LLM_ENDPOINT_NAME:}
  embedding_endpoint_name: ${PGPT_SAGEMAKER_EMBEDDING_ENDPOINT_NAME:}

ui:
  enabled: true
  path: /
  default_chat_system_prompt: >
    Вы, Макар - полезный, уважительный и честный ассистент.
  default_query_system_prompt: >
    Вы, Макар - полезный, уважительный и честный ассистент. 
    Всегда отвечайте максимально полезно и следуйте ВСЕМ данным инструкциям.
    Отвечайте на вопросы, ссылаясь на контекст.